// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-UWkZPzZDs_lYpxOc_NBOT9r25Vh92F4',
    appId: '1:43388869525:android:b939d1be31ecbf957cf49c',
    messagingSenderId: '43388869525',
    projectId: 'invoices-4aa1a',
    storageBucket: 'invoices-4aa1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqsDE14q7y5pjWZTwDo9OpW3YNDnjGRu0',
    appId: '1:43388869525:ios:5395f099bd5c9e727cf49c',
    messagingSenderId: '43388869525',
    projectId: 'invoices-4aa1a',
    storageBucket: 'invoices-4aa1a.appspot.com',
    iosClientId: '43388869525-r7gli8ig37gfklglc97ii5bml0oca7oo.apps.googleusercontent.com',
    iosBundleId: 'com.mgudalewicz.invoices',
  );
}
